#!/bin/bash
#
# Copyright Derek Macias (parts of code from NUT package)
# Copyright macester (parts of code from NUT package)
# Copyright gfjardim (parts of code from NUT package)
# Copyright SimonF (parts of code from NUT package)
# Copyright Lime Technology (any and all other parts of Unraid)
#
# Copyright desertwitch (as author and maintainer of this file)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License 2
# as published by the Free Software Foundation.
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
PROG="nafp"
PLGPATH="/boot/config/plugins/$PROG"
CONFIG=$PLGPATH/$PROG.cfg

echo "Starting AFP services (disks_mounted)..." | logger

if [ -e "$CONFIG" ]; then
    source "$CONFIG"
fi

if [ "$SERVICE" == "enable" ]; then
    TIMER=0
    while [ ! -d /mnt/user ]
    do
        sleep 1
        TIMER=$((TIMER+1))
        if [ $TIMER -ge 20 ]; then
            echo "AFP WARNING: /mnt/user never became available to open the AFP database." | logger
            echo "AFP WARNING: This could lead to unexpected AFP behaviour, check for other logs." | logger
            break
        fi
    done
    /etc/rc.d/rc.nafp start 2>&1 | logger
fi
